name: Django-Docker CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install kubectl
        uses: aws-actions/setup-kubectl@v1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: '${{ runner.os }}-pip-${{ hashFiles(''**/backend/requirements.txt'') }}'
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r /backend/requirements.txt

      - name: Run tests
        run: |
          python /backend/manage.py test

      - name: Build backend image
        run: |
          docker build -t d10-be:$GITHUB_SHA ./backend
          docker push d10-be:$GITHUB_SHA

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Build frontend image
        run: |
          docker build -t d10-fe:$GITHUB_SHA ./frontend
          docker push d10-fe:$GITHUB_SHA
  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        # ... (configure AWS credentials if needed)

      - name: Install kubectl
        uses: aws-actions/setup-kubectl@v1

      - name: Deploy to EKS Cluster
        run: |
          kubectl apply -f deploymentbe.yaml -f deploymentfe.yaml
